name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**/*'
      - 'ui/**/*'
      - 'emu/**/*'
      - '.github/workflows/**/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**/*'
      - 'ui/**/*'
      - 'emu/**/*'
      - '.github/workflows/**/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: dtolnay/rust-toolchain@stable
    - name: Check
      run: just check-fmt test lint

  check_after_rebase:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: dtolnay/rust-toolchain@stable
    - name: Check after rebase
      run: just check-after-rebase
