name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**/*'
      - 'ui/**/*'
      - 'emu/**/*'
      - '.github/workflows/**/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**/*'
      - 'ui/**/*'
      - 'emu/**/*'
      - '.github/workflows/**/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
    fail-fast: false
    matrix:
      os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: dtolnay/rust-toolchain@stable
    - name: Check
      run:
      - just check-fmt
      - just test
      - just lint

  check_after_rebase:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: dtolnay/rust-toolchain@stable
    - name: Check after rebase
      run:
      - git rebase main
      - CONFLICTS=$(git ls-files -u | wc -l)
      - if [ "$CONFLICTS" -gt 0 ] ; then exit 1 fi
      - just check-fmt
      - just test
      - just lint

  
